In [ ]:

import kagglehub
import pandas as pd
import re 
import matplotlib.pyplot as plt

In [644]:
import os

In [645]:
os.environ['KAGGLE_USERNAME'] = "nonso96"
os.environ['KAGGLE_KEY'] = "a0313a16ec2797805eb34e9f9afc7fcb"

In [646]:
#path = kagglehub.dataset_download("yagunnersya/fifa-21-messy-raw-dataset-for-cleaning-exploring")

In [647]:
print(path)

C:\Users\Princ\.cache\kagglehub\datasets\yagunnersya\fifa-21-messy-raw-dataset-for-cleaning-exploring\versions\2

In [648]:
file_path = os.path.join(path,"fifa21 raw data v2.csv")

In [649]:
csv = pd.read_csv(file_path)

C:\Users\Princ\AppData\Local\Temp\ipykernel_9968\1844339803.py:1: DtypeWarning: Columns (0: Hits) have mixed types. Specify dtype option on import or set low_memory=False.
  csv = pd.read_csv(file_path)

In [650]:
df = pd.DataFrame(csv)

In [651]:
df.columns

Index(['ID', 'Name', 'LongName', 'photoUrl', 'playerUrl', 'Nationality', 'Age',
       '↓OVA', 'POT', 'Club', 'Contract', 'Positions', 'Height', 'Weight',
       'Preferred Foot', 'BOV', 'Best Position', 'Joined', 'Loan Date End',
       'Value', 'Wage', 'Release Clause', 'Attacking', 'Crossing', 'Finishing',
       'Heading Accuracy', 'Short Passing', 'Volleys', 'Skill', 'Dribbling',
       'Curve', 'FK Accuracy', 'Long Passing', 'Ball Control', 'Movement',
       'Acceleration', 'Sprint Speed', 'Agility', 'Reactions', 'Balance',
       'Power', 'Shot Power', 'Jumping', 'Stamina', 'Strength', 'Long Shots',
       'Mentality', 'Aggression', 'Interceptions', 'Positioning', 'Vision',
       'Penalties', 'Composure', 'Defending', 'Marking', 'Standing Tackle',
       'Sliding Tackle', 'Goalkeeping', 'GK Diving', 'GK Handling',
       'GK Kicking', 'GK Positioning', 'GK Reflexes', 'Total Stats',
       'Base Stats', 'W/F', 'SM', 'A/W', 'D/W', 'IR', 'PAC', 'SHO', 'PAS',
       'DRI', 'DEF', 'PHY', 'Hits'],
      dtype='str')

In [652]:

weight = df['Weight'].astype(str).str.replace(r'[a-zA-Z]','',regex=True).astype(float)

In [653]:
df['Height']

0        170cm
1        187cm
2        188cm
3        181cm
4        175cm
         ...
18974    178cm
18975    175cm
18976    179cm
18977    175cm
18978    188cm
Name: Height, Length: 18979, dtype: str

In [654]:

height = df['Height'].astype(str).str.replace(r'[^0-9]','',regex=True).astype(float)

In [655]:
height

0        170.0
1        187.0
2        188.0
3        181.0
4        175.0
         ...
18974    178.0
18975    175.0
18976    179.0
18977    175.0
18978    188.0
Name: Height, Length: 18979, dtype: float64

In [656]:
df['Weight']= weight

In [657]:
df['Height'] =height

In [658]:
df

,ID,Name,LongName,photoUrl,playerUrl,Nationality,Age,↓OVA,POT,Club,...,A/W,D/W,IR,PAC,SHO,PAS,DRI,DEF,PHY,Hits
0,158023,L. Messi,Lionel Messi,https://cdn.sofifa.com/players/158/023/21_60.png,http://sofifa.com/player/158023/lionel-messi/2...,Argentina,33,93,93,\n\n\n\nFC Barcelona,...,Medium,Low,5 ★,85,92,91,95,38,65,771
1,20801,Cristiano Ronaldo,C. Ronaldo dos Santos Aveiro,https://cdn.sofifa.com/players/020/801/21_60.png,http://sofifa.com/player/20801/c-ronaldo-dos-s...,Portugal,35,92,92,\n\n\n\nJuventus,...,High,Low,5 ★,89,93,81,89,35,77,562
2,200389,J. Oblak,Jan Oblak,https://cdn.sofifa.com/players/200/389/21_60.png,http://sofifa.com/player/200389/jan-oblak/210006/,Slovenia,27,91,93,\n\n\n\nAtlético Madrid,...,Medium,Medium,3 ★,87,92,78,90,52,90,150
3,192985,K. De Bruyne,Kevin De Bruyne,https://cdn.sofifa.com/players/192/985/21_60.png,http://sofifa.com/player/192985/kevin-de-bruyn...,Belgium,29,91,91,\n\n\n\nManchester City,...,High,High,4 ★,76,86,93,88,64,78,207
4,190871,Neymar Jr,Neymar da Silva Santos Jr.,https://cdn.sofifa.com/players/190/871/21_60.png,http://sofifa.com/player/190871/neymar-da-silv...,Brazil,28,91,91,\n\n\n\nParis Saint-Germain,...,High,Medium,5 ★,91,85,86,94,36,59,595
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
18974,247223,Xia Ao,Ao Xia,https://cdn.sofifa.com/players/247/223/21_60.png,http://sofifa.com/player/247223/ao-xia/210006/,China PR,21,47,55,\n\n\n\nWuhan Zall,...,Medium,Medium,1 ★,64,28,26,38,48,51,NaN
18975,258760,B. Hough,Ben Hough,https://cdn.sofifa.com/players/258/760/21_60.png,http://sofifa.com/player/258760/ben-hough/210006/,England,17,47,67,\n\n\n\nOldham Athletic,...,Medium,Medium,1 ★,64,40,48,49,35,45,NaN
18976,252757,R. McKinley,Ronan McKinley,https://cdn.sofifa.com/players/252/757/21_60.png,http://sofifa.com/player/252757/ronan-mckinley...,England,18,47,65,\n\n\n\nDerry City,...,Medium,Medium,1 ★,63,39,44,46,40,53,NaN
18977,243790,Wang Zhen'ao,Zhen'ao Wang,https://cdn.sofifa.com/players/243/790/21_60.png,http://sofifa.com/player/243790/zhenao-wang/21...,China PR,20,47,57,\n\n\n\nDalian YiFang FC,...,Medium,Medium,1 ★,58,49,41,49,30,44,NaN
18978,252520,Zhou Xiao,Xiao Zhou,https://cdn.sofifa.com/players/252/520/21_60.png,http://sofifa.com/player/252520/xiao-zhou/210006/,China PR,21,47,57,\n\n\n\nDalian YiFang FC,...,Medium,Medium,1 ★,62,22,39,42,45,55,NaN

In [659]:
df['Joined']

0         Jul 1, 2004
1        Jul 10, 2018
2        Jul 16, 2014
3        Aug 30, 2015
4         Aug 3, 2017
             ...
18974    Jul 13, 2018
18975     Aug 1, 2020
18976     Mar 8, 2019
18977    Sep 22, 2020
18978    Jul 29, 2019
Name: Joined, Length: 18979, dtype: str

In [660]:
years_of_play = df['Joined'].astype(str).str.split(',',n=1).str[-1].astype('Int64')

In [661]:
play_duration = years_of_play[(2026 - years_of_play)>10].astype('Int64')

In [662]:
play_duration

0        2004
2        2014
3        2015
5        2014
9        2014
         ...
18390    2014
18416    2013
18781    2015
18915    2015
18917    2015
Name: Joined, Length: 1658, dtype: Int64

In [663]:
df['play_duration']= play_duration
df['play_duration']

0        2004
1        <NA>
2        2014
3        2015
4        <NA>
         ...
18974    <NA>
18975    <NA>
18976    <NA>
18977    <NA>
18978    <NA>
Name: play_duration, Length: 18979, dtype: Int64

In [664]:
players_above_10 = ['Name','Joined']
target= 'play_duration'
result = df.loc[df[target].notna(),players_above_10]
result

                    Name        Joined
0               L. Messi   Jul 1, 2004
2               J. Oblak  Jul 16, 2014
3           K. De Bruyne  Aug 30, 2015
5         R. Lewandowski   Jul 1, 2014
9          M. ter Stegen   Jul 1, 2014
...                  ...           ...
18390         J. Stevens   Jul 1, 2014
18416      B. Al Bahrani   Jul 1, 2013
18781          S. Callan   Jan 1, 2015
18915  Chen-Zeng Tailang  Feb 28, 2015
18917          Gao Xiang  Feb 13, 2015

[1658 rows x 2 columns]

In [665]:
df['Wage']

0        €560K
1        €220K
2        €125K
3        €370K
4        €270K
         ...
18974      €1K
18975     €500
18976     €500
18977      €2K
18978      €1K
Name: Wage, Length: 18979, dtype: str

In [666]:
def raw(x):
    x = str(x).strip().upper()
    cuurrency = x[0]
    value =(x[1:-1])
    multiplier = x[-1]
    if 'K' in x:
        return float(value)*1000
    elif 'M' in x:
        return float(value) *1000000
    else:
        return

In [667]:
df['Wages'] = df['Wage'].map(raw)
value = df['Value'].map(raw)
df['Wage'] = df['Wages']
df['Wage']

0        560000.0
1        220000.0
2        125000.0
3        370000.0
4        270000.0
           ...
18974      1000.0
18975         NaN
18976         NaN
18977      2000.0
18978      1000.0
Name: Wage, Length: 18979, dtype: float64

In [ ]:
df['Value']=value
df['Value']

0        103500000.0
1         63000000.0
2        120000000.0
3        129000000.0
4        132000000.0
            ...
18974       100000.0
18975       130000.0
18976       120000.0
18977       100000.0
18978       100000.0
Name: Value, Length: 18979, dtype: float64

In [669]:
star = df['IR']
star

0        5 ★
1        5 ★
2        3 ★
3        4 ★
4        5 ★
        ...
18974    1 ★
18975    1 ★
18976    1 ★
18977    1 ★
18978    1 ★
Name: IR, Length: 18979, dtype: str

In [670]:
def clear_star(x):
    x = str(x).strip()
    x =  re.findall('\\d',x)
    x = ''.join(x)
    return int(x)

In [671]:
star = star.map(clear_star)
star

0        5
1        5
2        3
3        4
4        5
        ..
18974    1
18975    1
18976    1
18977    1
18978    1
Name: IR, Length: 18979, dtype: int64

In [672]:
value = df['Value']
value

0        €103.5M
1           €63M
2          €120M
3          €129M
4          €132M
          ...
18974      €100K
18975      €130K
18976      €120K
18977      €100K
18978      €100K
Name: Value, Length: 18979, dtype: str

In [ ]:
plt.plot()